title: Srishti Jha # your name (or website title) here
logo:  "https://jaipurliteraturefestival.org/uploads_jaipurlitfest/speakers/4063-srishti-jha.jpeg"
description: > # your text below (remove <br> elements if you don't need line breaks)
 New Delhi, India
 <h3>Author| Writer </h3>
 <a href="https://www.twitter.com/jha_srishti">Connect on Twitter</a><br></br>
 See my <a href="https://drive.google.com/file/d/1Reuo8VzEUOhEsJG2_KAzuAOpGo2xuYU9/view?usp=share_link">resume</a>
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
